# Generated by Django 4.2.5 on 2023-09-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='interval',
            field=models.CharField(default='daily', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='interval',
            field=models.CharField(default='daily', max_length=8),
            preserve_default=False,
        ),
    ]
