# Generated by Django 4.2.5 on 2023-09-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_price_interval_stock_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='volume',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='price',
            name='stock',
            field=models.CharField(max_length=10),
        ),
    ]
