# Generated by Django 4.2.5 on 2023-09-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_rename_comprehensive_income_net_of_tax_income_comprehensiveincomenetoftax_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='costOfGoodsAndServicesSold',
            new_name='costofGoodsAndServicesSold',
        ),
    ]
