# Generated by Django 4.2.5 on 2023-09-30 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_rename_accumulateddepreciationamortizationppe_balance_accumulateddepreciationamortizationppe_and_mor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cash',
            old_name='paymentsForRepurchaseOfPreferred_stock',
            new_name='paymentsForRepurchaseOfPreferredStock',
        ),
        migrations.RenameField(
            model_name='cash',
            old_name='proceedsFromIssuanceOfCommon_stock',
            new_name='proceedsFromIssuanceOfCommonStock',
        ),
    ]
