# Generated by Django 4.2.5 on 2023-09-30 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_rename_paymentsforrepurchaseofpreferred_stock_cash_paymentsforrepurchaseofpreferredstock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.CharField(max_length=10)),
                ('AssetType', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500)),
                ('CIK', models.CharField(max_length=10)),
                ('Exchange', models.CharField(max_length=10)),
                ('Currency', models.CharField(max_length=10)),
                ('Country', models.CharField(max_length=10)),
                ('Sector', models.CharField(max_length=10)),
                ('Industry', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=100)),
                ('FiscalYearEnd', models.CharField(max_length=10)),
                ('LatestQuarter', models.CharField(max_length=10)),
                ('MarketCapitalization', models.FloatField()),
                ('EBITDA', models.FloatField()),
                ('PERatio', models.FloatField()),
                ('PEGRatio', models.FloatField()),
                ('BookValue', models.FloatField()),
                ('DividendPerShare', models.FloatField()),
                ('DividendYield', models.FloatField()),
                ('EPS', models.FloatField()),
                ('RevenuePerShareTTM', models.FloatField()),
                ('ProfitMargin', models.FloatField()),
                ('OperatingMarginTTM', models.FloatField()),
                ('ReturnOnAssetsTTM', models.FloatField()),
                ('ReturnOnEquityTTM', models.FloatField()),
                ('RevenueTTM', models.FloatField()),
                ('GrossProfitTTM', models.FloatField()),
                ('DilutedEPSTTM', models.FloatField()),
                ('QuarterlyEarningsGrowthYOY', models.FloatField()),
                ('QuarterlyRevenueGrowthYOY', models.FloatField()),
                ('AnalystTargetPrice', models.FloatField()),
                ('TrailingPE', models.FloatField()),
                ('ForwardPE', models.FloatField()),
                ('PriceToSalesRatioTTM', models.FloatField()),
                ('PriceToBookRatio', models.FloatField()),
                ('EVToRevenue', models.FloatField()),
                ('EVToEBITDA', models.FloatField()),
                ('Beta', models.FloatField()),
                ('FiftyTwoWeekHigh', models.FloatField()),
                ('FiftyTwoWeekLow', models.FloatField()),
                ('FiftyDayMovingAverage', models.FloatField()),
                ('TwoHundredDayMovingAverage', models.FloatField()),
                ('SharesOutstanding', models.FloatField()),
                ('DividendDate', models.DateTimeField(verbose_name='date')),
                ('ExDividendDate', models.DateTimeField(verbose_name='date')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
        ),
    ]
