# Generated by Django 4.2.5 on 2023-09-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_alter_balance_reportedcurrency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overview',
            name='Description',
            field=models.TextField(),
        ),
    ]
